export const EASY_WORDS = [
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
  "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
  "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
  "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
  "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
  "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
  "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
  "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
  "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
  "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
  "run", "walk", "jump", "play", "fast", "slow", "hot", "cold", "big", "small",
  "open", "close", "left", "right", "down", "yes", "stop", "start", "help", "need",
  "feel", "keep", "let", "put", "end", "why", "try", "ask", "hand", "high",
  "own", "last", "long", "great", "old", "off", "next", "few", "case", "man",
  "woman", "child", "world", "life", "hand", "part", "place", "week", "home", "room",
  "word", "fact", "head", "house", "water", "light", "night", "point", "power", "line",
] as const;

export const NORMAL_WORDS = [
  "about", "after", "again", "almost", "always", "another", "around", "because",
  "before", "between", "both", "change", "close", "could", "different", "during",
  "early", "enough", "every", "example", "family", "follow", "found", "friend",
  "great", "group", "happen", "important", "inside", "later", "learn", "leave",
  "little", "might", "never", "number", "often", "other", "people", "place",
  "problem", "question", "really", "right", "school", "second", "should", "small",
  "something", "still", "system", "their", "there", "these", "thing", "think",
  "those", "though", "through", "today", "together", "under", "until", "water",
  "where", "which", "while", "world", "would", "write", "young", "against",
  "already", "always", "among", "become", "better", "bring", "build", "called",
  "cannot", "certain", "common", "complete", "consider", "continue", "country",
  "course", "create", "decide", "develop", "direct", "effect", "either", "energy",
  "expect", "experience", "explain", "figure", "final", "force", "further",
  "general", "government", "however", "human", "include", "increase", "information",
  "interest", "itself", "level", "local", "major", "maybe", "means", "member",
  "mind", "moment", "move", "music", "name", "national", "nature", "necessary",
  "night", "nothing", "office", "once", "order", "others", "perhaps", "person",
  "possible", "power", "present", "pretty", "process", "program", "provide",
  "public", "quite", "rather", "reason", "recent", "remain", "report", "result",
  "return", "room", "run", "service", "several", "short", "shown", "since",
  "social", "special", "state", "story", "strong", "study", "such", "sure",
  "table", "taken", "talk", "term", "test", "therefore", "though", "three",
  "toward", "turn", "type", "understand", "usually", "value", "various", "view",
  "voice", "wait", "walk", "watch", "whether", "within", "without", "word",
  "attack", "defend", "strike", "combo", "focus", "tempo", "rhythm", "precision",
  "target", "damage", "shield", "charge", "burst", "chain", "clash", "arena",
] as const;

export const HARD_WORDS = [
  "absolute", "abundant", "accelerate", "accurate", "acknowledge", "advantage",
  "adventure", "algorithm", "ambition", "analysis", "announce", "apparent",
  "approach", "argument", "assemble", "atmosphere", "attention", "attitude",
  "authority", "available", "awareness", "balance", "behavior", "boundary",
  "brilliant", "calculate", "capacity", "category", "challenge", "character",
  "chemical", "civilian", "collapse", "combination", "comfortable", "committee",
  "community", "companion", "compare", "competition", "complex", "component",
  "computer", "condition", "confidence", "conflict", "conscious", "considerable",
  "constant", "construct", "contrast", "contribute", "convention", "conversation",
  "convince", "corporate", "critical", "cultural", "curious", "current",
  "dangerous", "decision", "definition", "delicate", "delivery", "demonstrate",
  "dependent", "describe", "design", "desperate", "determine", "development",
  "difference", "difficult", "dimension", "direction", "discipline", "discover",
  "discussion", "distance", "distinct", "distribute", "document", "dominant",
  "economic", "education", "efficient", "electric", "element", "emergency",
  "emphasis", "employee", "encourage", "engineer", "enormous", "environment",
  "equipment", "essential", "establish", "estimate", "evaluate", "evidence",
  "evolution", "examine", "excellent", "exception", "exchange", "executive",
  "existence", "expansion", "experience", "experiment", "explain", "explosion",
  "expression", "external", "facility", "familiar", "feature", "federal",
  "flexible", "foundation", "frequency", "function", "generate", "generation",
  "gradually", "guarantee", "historical", "identity", "immediate", "impact",
  "implement", "important", "improve", "include", "independent", "indicate",
  "individual", "industry", "influence", "initial", "innovation", "inquiry",
  "instance", "instruction", "integrate", "intelligence", "intention", "internal",
  "interpret", "invention", "investigate", "involve", "knowledge", "language",
  "leadership", "literature", "location", "logical", "maintain", "management",
  "material", "measure", "mechanism", "medical", "memory", "mention",
  "military", "mission", "mixture", "moderate", "monitor", "movement",
  "multiple", "mystery", "natural", "negative", "network", "normal",
  "objective", "observe", "obtain", "obvious", "occasion", "occupation",
  "occur", "operation", "opinion", "opportunity", "opposite", "option",
  "ordinary", "organize", "original", "outcome", "overall", "overcome",
  "parallel", "particular", "pattern", "perform", "permanent", "personal",
  "physical", "picture", "platform", "political", "popular", "position",
  "positive", "potential", "practical", "precise", "predict", "prepare",
  "pressure", "previous", "primary", "principle", "priority", "private",
  "procedure", "produce", "professional", "progress", "project", "promise",
  "property", "protect", "provide", "purpose", "quality", "quantity",
  "reaction", "reality", "recognize", "recommend", "recover", "reduce",
  "reference", "reflect", "region", "regular", "related", "relationship",
  "relative", "relevant", "reliable", "religion", "remember", "replace",
  "require", "research", "resource", "respect", "response", "responsible",
  "restore", "restrict", "result", "reveal", "review", "science",
  "security", "separate", "sequence", "serious", "session", "significant",
  "similar", "situation", "solution", "specific", "standard", "strategy",
  "structure", "success", "sufficient", "suggest", "support", "surprise",
  "survive", "technique", "technology", "temperature", "theory", "therefore",
  "thousand", "threaten", "through", "together", "transfer", "transform",
  "transport", "treat", "ultimate", "understand", "unexpected", "universe",
  "unusual", "useful", "various", "version", "visible", "volume",
  "weapon", "weather", "welcome", "whatever", "widespread", "willing",
] as const;

export const EXPERT_WORDS = [
  "abstraction", "acceleration", "acknowledgment", "acquiescence", "aesthetics",
  "algorithmic", "amalgamation", "anachronistic", "anthropology", "apocryphal",
  "architecture", "asynchronous", "bureaucracy", "calibration", "catastrophic",
  "circumference", "circumstantial", "clandestine", "collaboration", "commensurate",
  "compendium", "comprehension", "concatenation", "conflagration", "conjecture",
  "consciousness", "consequence", "constellation", "constitutional", "contemporary",
  "contradiction", "convoluted", "correlation", "countermeasure", "crystallize",
  "decomposition", "deliberation", "demarcation", "denominator", "deterministic",
  "dichotomy", "differentiation", "disambiguation", "discrepancy", "dissertation",
  "ebullient", "echelon", "effervescent", "egalitarian", "elaborately",
  "elliptical", "empirical", "encyclopedia", "ephemeral", "equilibrium",
  "equivocate", "esoteric", "etymology", "exacerbate", "exhilarating",
  "existential", "exponential", "extemporaneous", "extrapolate", "facetious",
  "fallacious", "fastidious", "fluctuation", "fortuitous", "fragmentation",
  "grandiloquent", "heuristic", "hierarchical", "hypothesis", "idiosyncratic",
  "illuminate", "immutable", "implementation", "inadvertently", "incandescent",
  "inconceivable", "independence", "indeterminate", "infrastructure", "initialization",
  "insurmountable", "intellectual", "intermittent", "interpretation", "intransigent",
  "irreconcilable", "juxtaposition", "kaleidoscope", "labyrinthine", "lexicography",
  "longitudinal", "luminescence", "magnanimous", "manifestation", "metamorphosis",
  "methodology", "microcosm", "miscellaneous", "multiplicity", "necessitate",
  "nomenclature", "obfuscation", "omnipresent", "orchestration", "paradigm",
  "parallelogram", "perpendicular", "perspicacious", "phenomenon", "philosophical",
  "photosynthesis", "precipitous", "predisposition", "procrastinate", "proliferation",
  "quintessential", "ramification", "recalibration", "reciprocity", "reconciliation",
  "reminiscence", "repercussion", "resilience", "retrospective", "rhapsodic",
  "sacrosanct", "simultaneous", "sophisticated", "subterranean", "superfluous",
  "surreptitious", "synchronous", "transcendental", "unprecedented", "verisimilitude",
  "vicissitude", "vocabulary", "vulnerability", "zeitgeist",
] as const;

export const PROGRAMMING_WORDS = [
  "function", "return", "const", "let", "var", "class", "interface", "type",
  "import", "export", "async", "await", "promise", "callback", "closure",
  "module", "package", "compile", "runtime", "debug", "stack", "heap",
  "array", "object", "string", "boolean", "number", "null", "undefined",
  "react", "component", "props", "state", "hook", "effect", "memo",
  "reducer", "context", "query", "mutation", "schema", "index", "cache",
  "server", "client", "request", "response", "header", "cookie", "token",
  "route", "middleware", "handler", "exception", "throw", "catch", "finally",
  "loop", "while", "switch", "case", "break", "continue", "yield",
  "binary", "bitwise", "hash", "tree", "graph", "queue", "deque",
  "thread", "process", "mutex", "lock", "atomic", "latency", "throughput",
  "refactor", "lint", "test", "assert", "mock", "fixture", "snapshot",
  "typescript", "javascript", "python", "rust", "golang", "kotlin",
  "algorithm", "complexity", "recursion", "iteration", "immutable",
] as const;

export const FANTASY_WORDS = [
  "dragon", "castle", "sword", "shield", "quest", "rune", "mage", "spell",
  "potion", "dungeon", "knight", "ranger", "oracle", "phoenix", "griffin",
  "ember", "frost", "shadow", "realm", "crown", "sigil", "grimoire",
  "enchant", "summon", "ward", "blade", "armor", "cloak", "amulet",
  "goblin", "troll", "wraith", "lich", "hydra", "wyvern", "basilisk",
  "temple", "forest", "cavern", "bridge", "tower", "keep", "moat",
  "legend", "myth", "omen", "fate", "oath", "banish", "ascend",
  "crystal", "arcane", "void", "storm", "flame", "tide", "thorn",
] as const;

export const SCIFI_WORDS = [
  "quantum", "plasma", "neutron", "orbit", "signal", "probe", "android",
  "cyborg", "laser", "warp", "hyperspace", "nebula", "asteroid", "colony",
  "module", "reactor", "shield", "thruster", "drone", "satellite",
  "protocol", "uplink", "mainframe", "neural", "synthetic", "carbon",
  "oxygen", "gravity", "vacuum", "ion", "photon", "fusion", "core",
  "station", "hangar", "airlock", "cockpit", "nav", "beacon", "relay",
  "terraform", "genome", "clone", "hive", "swarm", "anomaly", "rift",
  "circuit", "processor", "firmware", "payload", "vector", "matrix",
] as const;

export const GAMING_WORDS = [
  "combo", "crit", "dodge", "parry", "block", "dash", "ult", "buff",
  "nerf", "spawn", "respawn", "loot", "quest", "raid", "boss", "wave",
  "arena", "match", "rank", "elo", "streak", "clutch", "aggro", "kite",
  "peek", "strafe", "reload", "ammo", "mana", "stamina", "cooldown",
  "hitbox", "lag", "ping", "frame", "input", "macro", "bind", "sens",
  "carry", "feed", "tilt", "gg", "wp", "mid", "lane", "jungle",
  "objective", "payload", "checkpoint", "speedrun", "nohit", "perfect",
] as const;

export const SENTENCES = [
  "Every keystroke is a strike if you keep your timing clean.",
  "The dummy learns nothing but it still refuses to fall.",
  "Speed without accuracy is just noise in a loud room.",
  "Hold the line, breathe, and let the next word land.",
  "A broken combo is not the end unless you stop typing.",
  "The arena lights flicker whenever a perfect word connects.",
  "Focus on the caret and the rest of the world can wait.",
  "Longer words hit harder but they also punish hesitation.",
  "You do not need to rush the first second of a fight.",
  "Reset your hands, reset your eyes, then start again.",
  "The boss does not blink so neither should your rhythm.",
  "Type like you mean it and the damage will follow.",
  "Small mistakes stack faster than a good streak can save you.",
  "Keep your shoulders down and your fingers close to home row.",
  "The last ten seconds are where most runs are decided.",
] as const;

export const QUOTES = [
  "We are what we repeatedly do. Excellence then is not an act but a habit.",
  "The secret of getting ahead is getting started.",
  "It is not the mountain we conquer but ourselves.",
  "A journey of a thousand miles begins with a single step.",
  "Fortune favors the bold.",
  "Know thyself.",
  "I think therefore I am.",
  "The only thing we have to fear is fear itself.",
  "To be or not to be that is the question.",
  "All that we see or seem is but a dream within a dream.",
  "The unexamined life is not worth living.",
  "Time is the wisest counselor of all.",
  "No man ever steps in the same river twice.",
  "The harder the conflict the more glorious the triumph.",
  "Well begun is half done.",
  "Silence is a true friend who never betrays.",
  "He who has a why to live can bear almost any how.",
  "What we achieve inwardly will change outer reality.",
  "Do what you can with what you have where you are.",
  "Action is the foundational key to all success.",
] as const;
